name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (if you're using a submodule for your theme)

      - name: Setup Hugo
        uses: somakaushik98/Personal_Portfolio
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: somakaushik98/Personal_Portfolio
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
